version: '3.8'
services:
    db:
        image: mariadb:10.7.4-focal
        container_name: '${DB_DOCKER_NAME}'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'cinemadb:/var/lib/mysql'
        networks:
            - cinewww
    php:
        build:
            context: ./docker
            dockerfile: PhpDockerFile
            args:
                WWWGROUP: '${WWWGROUP}'
                USER: '${USER}'
        image: cinedockphp
        container_name: '${PHP_DOCKER_NAME}'
        volumes:
            - '.:/var/www/html'
        ports:
            - 3002:3002
            - 3003:3003
        networks:
            - cinewww
        depends_on:
            - db
    web:
        build:
            context: ./docker
            dockerfile: NginxDockerFile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: cinedockwww
        container_name: '${WEB_DOCKER_NAME}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - cinewww
        depends_on:
            - php
networks:
    cinewww:
        driver: bridge
volumes:
    cinemadb:
        driver: local
